### ISSUE TITLE
"Not implemented" popunder alerts

### ISSUE THREAD

**Issue by Plasmmer** [ScreensOS/Screens#142]

**Comment by DaniellMesquita** [comment]
Next missions:

- [ ] Can open dialogs in other elements instead of only buttons
- [ ] Full-width dialogs
- [ ] Not fully dependence in metro.js API
- [ ] More colors for different dialog categories

**Comment by Plasmmer** [comment]
Duplicate of: https://github.com/ScreensOS/Screens/issues/63.
